default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: telerank_pl_development

production:
  adapter: mysql2
  encoding: utf8
  host: localhost
  pool: 5
  database: telerank_pl
  username: deploy
  password: 123qwe!@#QWE
